---

- name: stop and disable
  become: true
  become_user: root
  ignore_errors: true
  with_items:
    - "9.6"
    - "10"
  service:
    name: postgresql-{{ item }}-default.service
    state: stopped
    enabled: false
